### ISSUE TITLE
Objects array

### ISSUE THREAD

**Issue by abhisheksharma662** [manishjanky/ngx-select-dropdown#109]
displayKey:"description", //if objects array passed which key to be displayed defaults to description

key to display from array is available but 

how do we pass the value ? 
there is no key to pass the value from array

**Comment by abhisheksharma662** [comment]
not working with universal 

throwing error 

/home/abhishek/Documents/abhishek/connx_6/node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.js:9
import { Component, Input, EventEmitter, Output, HostListener, ViewChildren, ElementRef, ChangeDetectorRef, forwardRef } from "@angular/core";
       ^

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.l2Uu (/home/abhishek/Documents/abhishek/connx_6/dist-server/main.bundle.js:1:1464866)
    at e (/home/abhishek/Documents/abhishek/connx_6/dist-server/main.bundle.js:1:220)
    at Object.zQrb (/home/abhishek/Documents/abhishek/connx_6/dist-server/main.bundle.js:1:1836226)
    at e (/home/abhishek/Documents/abhishek/connx_6/dist-server/main.bundle.js:1:220)
    at Object.Ub9p (/home/abhishek/Documents/abhishek/connx_6/dist-server/main.bundle.js:1:935036)

**Comment by abhisheksharma662** [comment]
no reply ?

how many days more i need to wait ?

**Comment by manishjanky** [comment]
@abhisheksharma662  you dont need to pass the value.. You need to pass the key name i.e.
Suppose you have an object {firstName:'xxxx', lastName:'yyyyy'} and you firstName to be displayed in the list.. Your config should look like..
config = {
 ....
displayKey: 'firstName',
....
}

And to answer you second question Server Side rendering is not yet supported.. Please keep a watch will be included soon..
